-- Bếp Sỉ F&B - Initial catalog seed
-- Scope: product/category scaffold only.
-- Excluded by decision: merchant profile, delivery routes.
-- All imported products stay in needs_review until admin verifies price/spec/image.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Main categories / primary tabs
INSERT INTO categories (name, slug, sort_order, is_active)
VALUES
  ('Tất cả', 'all', 0, true),
  ('Trà sữa & pha chế', 'tra-sua-pha-che', 10, true),
  ('Mì cay', 'mi-cay-han-quoc', 20, true),
  ('Đông lạnh', 'thuc-pham-dong-lanh', 30, true),
  ('Combo công thức', 'combo-cong-thuc', 40, true),
  ('Thương hiệu', 'brand-distribution', 50, true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active;

-- Subcategories
INSERT INTO categories (name, slug, parent_id, sort_order, is_active)
VALUES
  ('Trà nền / Trà túi lọc / Trà pha máy', 'tra-nen-tra-tui-loc', (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'), 101, true),
  ('Bột sữa / Bột béo / Creamer', 'bot-sua-bot-beo', (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'), 102, true),
  ('Topping', 'topping', (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'), 103, true),
  ('Syrup / Sốt / Mứt / Trái cây ngâm', 'syrup-sot-mut', (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'), 104, true),
  ('Bột pudding / Jelly / Thạch', 'bot-pudding-jelly', (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'), 105, true),
  ('Nguyên liệu đá xay', 'nguyen-lieu-da-xay', (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'), 106, true),
  ('Nước cốt dừa / Coconut base', 'cot-dua', (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'), 107, true),
  ('Mì / Sốt / Gia vị mì cay', 'mi-cay-base', (SELECT id FROM categories WHERE slug = 'mi-cay-han-quoc'), 201, true),
  ('Topping mì cay', 'topping-mi-cay', (SELECT id FROM categories WHERE slug = 'mi-cay-han-quoc'), 202, true),
  ('Xiên que / Ăn vặt', 'xien-que-an-vat', (SELECT id FROM categories WHERE slug = 'thuc-pham-dong-lanh'), 301, true),
  ('Viên thả lẩu / topping đông lạnh', 'vien-tha-lau', (SELECT id FROM categories WHERE slug = 'thuc-pham-dong-lanh'), 302, true),
  ('Đồ chiên đông lạnh', 'do-chien-dong-lanh', (SELECT id FROM categories WHERE slug = 'thuc-pham-dong-lanh'), 303, true),
  ('Combo mở quán', 'combo-mo-quan', (SELECT id FROM categories WHERE slug = 'combo-cong-thuc'), 401, true),
  ('Công thức trà sữa', 'cong-thuc-tra-sua', (SELECT id FROM categories WHERE slug = 'combo-cong-thuc'), 402, true),
  ('Công thức trà trái cây', 'cong-thuc-tra-trai-cay', (SELECT id FROM categories WHERE slug = 'combo-cong-thuc'), 403, true),
  ('Công thức đồ uống nóng', 'cong-thuc-do-uong-nong', (SELECT id FROM categories WHERE slug = 'combo-cong-thuc'), 404, true),
  ('SUMI', 'brand-sumi', (SELECT id FROM categories WHERE slug = 'brand-distribution'), 501, true),
  ('PRINCE', 'brand-prince', (SELECT id FROM categories WHERE slug = 'brand-distribution'), 502, true),
  ('BARISMATE', 'brand-barismate', (SELECT id FROM categories WHERE slug = 'brand-distribution'), 503, true),
  ('MAGISEA', 'brand-magisea', (SELECT id FROM categories WHERE slug = 'brand-distribution'), 504, true),
  ('SAWASDEE', 'brand-sawasdee', (SELECT id FROM categories WHERE slug = 'brand-distribution'), 505, true),
  ('ONA', 'brand-ona', (SELECT id FROM categories WHERE slug = 'brand-distribution'), 506, true),
  ('Lộc Phát', 'brand-loc-phat', (SELECT id FROM categories WHERE slug = 'brand-distribution'), 507, true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  parent_id = EXCLUDED.parent_id,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active;

-- Product review scaffold from public catalog snippets.
-- Important: status = needs_review and is_active = false by default.
INSERT INTO products (
  sku,
  slug,
  name,
  brand,
  category_id,
  subcategory_id,
  industry_group,
  product_type,
  short_description,
  description,
  origin,
  package_spec,
  package_size,
  unit,
  base_price,
  wholesale_price,
  min_order_qty,
  stock_status,
  is_active,
  status,
  sort_order,
  use_cases,
  tags,
  selling_points,
  source_confidence
)
VALUES
  (
    'TRA-ONA',
    'tra-ona',
    'Trà ONA',
    'ONA',
    (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'),
    (SELECT id FROM categories WHERE slug = 'tra-nen-tra-tui-loc'),
    'tra_sua_pha_che',
    'physical',
    'Trà nền dùng cho trà trái cây, trà sữa và các dòng trà pha máy.',
    'Trà nền dùng cho trà trái cây, trà sữa và các dòng trà pha máy. Cần admin xác minh quy cách, giá và hình ảnh trước khi active.',
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    1,
    'available',
    false,
    'needs_review',
    10,
    '["trà trái cây", "trà sữa", "trà pha máy"]'::jsonb,
    '["tra-nen", "tra-pha-may", "menu-quan", "ona"]'::jsonb,
    '["dùng làm dòng trà nền", "phù hợp menu quán"]'::jsonb,
    'public-snippet'
  ),
  (
    'TRA-LOC-PHAT',
    'tra-loc-phat',
    'Trà Lộc Phát',
    'Lộc Phát',
    (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'),
    (SELECT id FROM categories WHERE slug = 'tra-nen-tra-tui-loc'),
    'tra_sua_pha_che',
    'physical',
    'Trà nền gắn với các bộ công thức trà trái cây và menu dễ pha dễ bán.',
    'Trà nền dùng cho trà trái cây, trà sữa và công thức kinh doanh. Cần admin xác minh quy cách, giá và hình ảnh trước khi active.',
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    1,
    'available',
    false,
    'needs_review',
    20,
    '["trà trái cây", "trà sữa", "công thức kinh doanh"]'::jsonb,
    '["tra-nen", "tra-trai-cay", "loc-phat", "cong-thuc"]'::jsonb,
    '["gắn với bộ công thức trà trái cây", "dễ pha dễ bán"]'::jsonb,
    'public-snippet'
  ),
  (
    'BOT-SUA-SAWASDEE-1KG',
    'bot-sua-sawasdee-1kg',
    'Bột sữa Sawasdee 1kg',
    'SAWASDEE',
    (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'),
    (SELECT id FROM categories WHERE slug = 'bot-sua-bot-beo'),
    'tra_sua_pha_che',
    'physical',
    'Bột sữa pha chế 1kg, xuất xứ Thái Lan, dùng cho trà sữa và đồ uống béo sữa.',
    'Bột sữa pha chế dùng cho trà sữa và đồ uống béo sữa. Cần admin xác minh giá và hình ảnh trước khi active.',
    'Thái Lan',
    '1kg',
    '1kg',
    'gói',
    0,
    NULL,
    1,
    'available',
    false,
    'needs_review',
    30,
    '["trà sữa", "đồ uống béo sữa", "menu quán"]'::jsonb,
    '["bot-sua", "creamer", "sawasdee", "thai-lan"]'::jsonb,
    '["hòa tan tốt", "không vón cục", "sánh mịn", "thơm béo"]'::jsonb,
    'confirmed-public-post-snippet'
  ),
  (
    'TRAN-CHAU-5S-DAI-LOAN',
    'tran-chau-5s-dai-loan',
    'Trân châu 5s chuẩn vị Đài Loan',
    NULL,
    (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'),
    (SELECT id FROM categories WHERE slug = 'topping'),
    'tra_sua_pha_che',
    'physical',
    'Topping trân châu dùng cho trà sữa và đồ uống pha chế.',
    'Topping trân châu dùng cho trà sữa và đồ uống pha chế. Cần admin xác minh thương hiệu, quy cách, giá và hình ảnh trước khi active.',
    'TODO xác minh',
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    1,
    'available',
    false,
    'needs_review',
    40,
    '["trà sữa", "topping đồ uống"]'::jsonb,
    '["tran-chau", "topping", "dai-loan"]'::jsonb,
    '["thơm ngon", "chuẩn vị Đài Loan"]'::jsonb,
    'public-snippet'
  ),
  (
    'SYRUP-PRINCE',
    'syrup-prince',
    'Syrup PRINCE',
    'PRINCE',
    (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'),
    (SELECT id FROM categories WHERE slug = 'syrup-sot-mut'),
    'tra_sua_pha_che',
    'physical',
    'Syrup dùng cho trà trái cây, soda, đá xay và các món pha chế có hương vị.',
    'Syrup PRINCE dùng cho trà trái cây, soda, đá xay và topping flavor. Cần admin xác minh vị, quy cách, giá và hình ảnh trước khi active.',
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    1,
    'available',
    false,
    'needs_review',
    50,
    '["trà trái cây", "soda", "đá xay", "topping flavor"]'::jsonb,
    '["syrup", "prince", "tra-trai-cay", "da-xay"]'::jsonb,
    '["nhóm sản phẩm PRINCE", "phù hợp menu pha chế"]'::jsonb,
    'inferred-category'
  ),
  (
    'DAO-NGAM-DUONG-PRINCE',
    'dao-ngam-duong-prince',
    'Đào ngâm đường PRINCE',
    'PRINCE',
    (SELECT id FROM categories WHERE slug = 'tra-sua-pha-che'),
    (SELECT id FROM categories WHERE slug = 'syrup-sot-mut'),
    'tra_sua_pha_che',
    'physical',
    'Đào ngâm đường dùng cho trà đào và các món trà trái cây.',
    'Đào ngâm đường PRINCE dùng cho trà đào, trà trái cây và topping trái cây. Cần admin xác minh quy cách, giá và hình ảnh trước khi active.',
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    1,
    'available',
    false,
    'needs_review',
    60,
    '["trà đào", "trà trái cây", "topping trái cây"]'::jsonb,
    '["dao-ngam", "prince", "tra-trai-cay"]'::jsonb,
    '["nhóm sản phẩm PRINCE", "ứng dụng trà đào"]'::jsonb,
    'inferred-category'
  ),
  (
    'MI-CAY-HAN-QUOC-BASE',
    'mi-cay-han-quoc-base',
    'Nguyên liệu mì cay Hàn Quốc',
    NULL,
    (SELECT id FROM categories WHERE slug = 'mi-cay-han-quoc'),
    (SELECT id FROM categories WHERE slug = 'mi-cay-base'),
    'mi_cay_han_quoc',
    'physical',
    'Nhóm nguyên liệu cho quán mì cay và món ăn vặt.',
    'Scaffold ngành hàng mì cay Hàn Quốc. Cần nhập SKU thật, quy cách, giá và hình ảnh từ kho trước khi active.',
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    1,
    'available',
    false,
    'needs_review',
    70,
    '["quán mì cay", "quán ăn vặt"]'::jsonb,
    '["mi-cay", "han-quoc", "nguyen-lieu"]'::jsonb,
    '["ngành hàng chính", "cần bổ sung SKU cụ thể"]'::jsonb,
    'inferred-category'
  ),
  (
    'THUC-PHAM-DONG-LANH-GENERAL',
    'thuc-pham-dong-lanh-general',
    'Thực phẩm đông lạnh',
    NULL,
    (SELECT id FROM categories WHERE slug = 'thuc-pham-dong-lanh'),
    NULL,
    'thuc_pham_dong_lanh',
    'physical',
    'Nhóm thực phẩm đông lạnh cho quán ăn vặt, trà sữa và mì cay.',
    'Scaffold ngành hàng thực phẩm đông lạnh. Cần nhập SKU thật, quy cách, giá và hình ảnh từ kho trước khi active.',
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    1,
    'available',
    false,
    'needs_review',
    80,
    '["quán ăn vặt", "quán trà sữa", "quán mì cay"]'::jsonb,
    '["dong-lanh", "an-vat", "mi-cay"]'::jsonb,
    '["ngành hàng chính", "cần bổ sung SKU cụ thể"]'::jsonb,
    'inferred-category'
  )
ON CONFLICT (sku) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category_id = EXCLUDED.category_id,
  subcategory_id = EXCLUDED.subcategory_id,
  industry_group = EXCLUDED.industry_group,
  product_type = EXCLUDED.product_type,
  short_description = EXCLUDED.short_description,
  description = EXCLUDED.description,
  origin = EXCLUDED.origin,
  package_spec = EXCLUDED.package_spec,
  package_size = EXCLUDED.package_size,
  unit = EXCLUDED.unit,
  min_order_qty = EXCLUDED.min_order_qty,
  stock_status = EXCLUDED.stock_status,
  is_active = EXCLUDED.is_active,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  use_cases = EXCLUDED.use_cases,
  tags = EXCLUDED.tags,
  selling_points = EXCLUDED.selling_points,
  source_confidence = EXCLUDED.source_confidence;
