/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js in normal projects.
// It is kept here so typecheck has a stable starting point.
