import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { getDb } from "../src/db/pool";
import type { StaffIdentity } from "../src/modules/auth/auth.identity";
import { AiRecipeDraftService } from "../src/modules/ai/ai-recipe-draft.service";
import { AiProjectStoreError } from "../src/modules/ai/ai-project-store.service";

async function expectStoreError(run: () => Promise<unknown>, code: string) {
  await assert.rejects(
    run,
    (error: unknown) => error instanceof AiProjectStoreError && error.code === code,
    `Expected AiProjectStoreError ${code}`,
  );
}

function recipePayload(title: string) {
  return {
    title,
    shortDescription: "AI draft recipe for admin review.",
    description: "Draft recipe generated by the controlled AI pipeline.",
    relatedBrand: "Bếp Sỉ",
    estimatedCost: "120000",
    suggestedPrice: "180000",
    ingredients: [
      { name: "Trà đen", quantity: "50", unit: "g", note: "Ủ vừa đủ", optional: false },
      { name: "Đào ngâm", quantity: "200", unit: "g", optional: false },
    ],
    steps: [
      { title: "Ủ trà", content: "Ủ trà đen với nước nóng theo định lượng." },
      { title: "Hoàn thiện", content: "Thêm đào, đá và khuấy đều trước khi phục vụ." },
    ],
  };
}

async function createAiDraft(
  admin: StaffIdentity,
  options: {
    status?: string;
    applyStatus?: string;
    validationStatus?: string;
    useCase?: string;
    payload?: unknown;
  },
) {
  const db = getDb();
  const suffix = randomUUID().slice(0, 8);
  const project = await db.query<{ id: string }>(
    `INSERT INTO ai_projects (project_key,name,created_by_staff_id)
     VALUES ($1,$2,$3)
     RETURNING id`,
    [`a1g-${suffix}`, `A1g ${suffix}`, admin.staffId],
  );
  const version = await db.query<{ id: string }>(
    `INSERT INTO ai_project_versions (project_id,version,schema_version,file_hash,json_payload,created_by_staff_id)
     VALUES ($1,1,'1.0',$2,'{}'::jsonb,$3)
     RETURNING id`,
    [project.rows[0].id, `hash-${suffix}`, admin.staffId],
  );
  await db.query("UPDATE ai_projects SET active_version_id=$1 WHERE id=$2", [version.rows[0].id, project.rows[0].id]);
  const model = await db.query<{ id: string }>(
    `INSERT INTO ai_project_models (project_version_id,model_key,provider,model_id,display_name)
     VALUES ($1,'quality','vertex_ai','gemini-test','Gemini Test')
     RETURNING id`,
    [version.rows[0].id],
  );
  const agent = await db.query<{ id: string }>(
    `INSERT INTO ai_project_agents (
       project_version_id,agent_key,name,use_case,model_key,input_schema,output_schema,review_status,is_enabled
     ) VALUES ($1,'recipe-agent','Recipe Agent',$2,'quality','{}'::jsonb,'{}'::jsonb,'approved',true)
     RETURNING id`,
    [version.rows[0].id, options.useCase || "recipe_draft"],
  );
  const document = await db.query<{ id: string }>(
    `INSERT INTO ai_documents (
       source,status,project_version_id,agent_id,model_id,schema_version,json_payload,
       validation_status,validation_errors,created_by_staff_id,updated_by_staff_id,
       reviewed_by_staff_id,reviewed_at,apply_status
     ) VALUES ('ai',$1,$2,$3,$4,'1.0',$5::jsonb,$6,'[]'::jsonb,$7,$7,$7,now(),$8)
     RETURNING id`,
    [
      options.status || "approved",
      version.rows[0].id,
      agent.rows[0].id,
      model.rows[0].id,
      JSON.stringify(options.payload ?? recipePayload(`Trà đào A1g ${suffix}`)),
      options.validationStatus || "valid",
      admin.staffId,
      options.applyStatus || "pending_apply",
    ],
  );
  return { documentId: document.rows[0].id, projectId: project.rows[0].id };
}

async function main() {
  const db = getDb();
  const service = new AiRecipeDraftService(db);
  const suffix = randomUUID().slice(0, 8);
  const admin: StaffIdentity = {
    kind: "staff",
    clerkUserId: `clerk-a1g-${suffix}`,
    staffId: randomUUID(),
    role: "admin",
    isActive: true,
  };
  const projectIds: string[] = [];
  const recipeIds: string[] = [];

  await db.query(
    `INSERT INTO staff_users (id, clerk_user_id, name, role, is_active)
     VALUES ($1,$2,'A1g Admin','admin',true)`,
    [admin.staffId, admin.clerkUserId],
  );

  try {
    const ready = await createAiDraft(admin, {});
    projectIds.push(ready.projectId);
    const created = await service.createRecipeDraft(admin, ready.documentId);
    recipeIds.push(created.recipe.id);

    assert.equal(created.recipe.status, "draft");
    assert.match(created.recipe.slug, /^tra-dao-a1g-/);
    assert.equal(created.counts.ingredients, 2);
    assert.equal(created.counts.steps, 2);
    assert.equal(created.document.applyStatus, "applied");
    assert.equal(created.document.version, 2);

    const recipe = await db.query(
      `SELECT slug,title,status,source_confidence FROM recipes WHERE id=$1`,
      [created.recipe.id],
    );
    assert.equal(recipe.rowCount, 1);
    assert.equal(recipe.rows[0].status, "draft");
    assert.equal(recipe.rows[0].source_confidence, "needs_review");

    const ingredients = await db.query(
      `SELECT name,quantity::text,unit,optional FROM recipe_ingredients WHERE recipe_id=$1 ORDER BY sort_order`,
      [created.recipe.id],
    );
    assert.equal(ingredients.rowCount, 2);
    assert.equal(ingredients.rows[0].name, "Trà đen");
    assert.equal(ingredients.rows[0].quantity, "50.00");
    assert.equal(ingredients.rows[0].optional, false);

    const steps = await db.query(
      `SELECT step_no,title,content FROM recipe_steps WHERE recipe_id=$1 ORDER BY step_no`,
      [created.recipe.id],
    );
    assert.equal(steps.rowCount, 2);
    assert.equal(steps.rows[0].step_no, 1);
    assert.equal(steps.rows[0].title, "Ủ trà");

    const link = await db.query(
      `SELECT document_id,recipe_id,actor_staff_id,source_payload FROM ai_recipe_draft_links WHERE document_id=$1`,
      [ready.documentId],
    );
    assert.equal(link.rowCount, 1);
    assert.equal(link.rows[0].recipe_id, created.recipe.id);
    assert.equal(link.rows[0].actor_staff_id, admin.staffId);
    assert.equal(link.rows[0].source_payload.title, recipe.rows[0].title);

    await expectStoreError(() => service.createRecipeDraft(admin, ready.documentId), "AI_DRAFT_NOT_READY");

    const notApproved = await createAiDraft(admin, { status: "draft" });
    projectIds.push(notApproved.projectId);
    await expectStoreError(() => service.createRecipeDraft(admin, notApproved.documentId), "AI_DRAFT_NOT_APPROVED");

    const wrongUseCase = await createAiDraft(admin, { useCase: "catalog_enrichment" });
    projectIds.push(wrongUseCase.projectId);
    await expectStoreError(() => service.createRecipeDraft(admin, wrongUseCase.documentId), "AI_DRAFT_USE_CASE_MISMATCH");

    const invalidPayload = await createAiDraft(admin, { payload: { title: "Missing arrays" } });
    projectIds.push(invalidPayload.projectId);
    await expectStoreError(() => service.createRecipeDraft(admin, invalidPayload.documentId), "INVALID_RECIPE_DRAFT_PAYLOAD");

    const invalidDraft = await createAiDraft(admin, { validationStatus: "invalid" });
    projectIds.push(invalidDraft.projectId);
    await expectStoreError(() => service.createRecipeDraft(admin, invalidDraft.documentId), "AI_DRAFT_INVALID");

    console.log("AI A1g recipe draft integration passed.");
  } finally {
    if (recipeIds.length > 0) {
      await db.query("DELETE FROM recipes WHERE id = ANY($1::uuid[])", [recipeIds]).catch(() => undefined);
    }
    if (projectIds.length > 0) {
      await db.query("DELETE FROM ai_projects WHERE id = ANY($1::uuid[])", [projectIds]).catch(() => undefined);
    }
    await db.query("DELETE FROM staff_users WHERE id=$1", [admin.staffId]).catch(() => undefined);
    await db.end();
  }
}

main().catch(async (error) => {
  console.error(error instanceof Error ? error.stack : error);
  await getDb().end().catch(() => undefined);
  process.exitCode = 1;
});
