-- Bếp Sỉ F&B - DB schema v1
-- Source of truth: db/migrations/001_init_core.sql
-- Apply on PostgreSQL / Heroku Postgres with:
--   psql "$DATABASE_URL" -f db/migrations/001_init_core.sql
-- Optional dev seed:
--   psql "$DATABASE_URL" -f db/seeds/001_seed_test.sql
--
-- Không giữ schema draft trùng lặp ở đây để tránh lệch migration.
-- Khi thêm bảng/cột mới: tạo migration mới trước, rồi cập nhật ghi chú file này nếu cần.
